language: go

go:
  - "1.8"  # 指定Golang 1.8

# Specify which branches to build using a safelist
# 分支白名单限制: 只有hugo分支的提交才会触发构建
branches:
  only:
    - master

# install:
# # 安装最新的hugo
#   - go get github.com/spf13/hugo 
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.56.1/hugo_0.56.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - ls
    - pwd

before_script:
 - git config --global user.name "yeqi"
 - git config --global user.email "qi.ye.siat@gmail.com"
script:
# 运行hugo命令
  - hugo

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip_cleanup: true # 重要，不能省略
  local_dir: public # 静态站点文件所在目录
  target_branch: master # 要将静态站点文件发布到哪个分支
  github_token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  #fqdn: blog.yuantops.com # 如果是自定义域名，此处要填
  keep_history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master # 博客源码的分支
  target_branch: master
  repo: yeqi17/yeqi17.github.io
  email: deploy@travis-ci.org
  name: deployment-bot
