baseURL = "https://yeqi17.github.io/"
languageCode = "en-us"
theme = "vienna"
title = "Practice Makes Perfect"
copyright = '&copy; Theme from <a href="https://themes.gohugo.io/vienna/">vienna</a> '

[params]
    subtitle = "Just do it" 
